#!/usr/bin/env sh

# hit the reset button.
echo 'rm -rf expoutput/'
rm -rf expoutput/
echo 'mkdir -p expoutput/'
mkdir -p expoutput/

# for each train txt file, hmm.py will find the corresponding test file.
for datafile in `ls data/*train.txt | sort`
do
	echo "generating csvs for $datafile ..."
	# test ngrams up to 6.
	# alpha = 1..4, beta = 1..5 ????
	for ng in 2 3 4
	do
		for alph in 1
		do
			echo "generating for n = $ng , alpha = $alph for beta = 1"
			for bet in 1
			do
				python ./hmm.py $datafile $ng $alph $bet
			done
		done
	done
done

# make a zip
echo 'rm -f hmmexperiments.zip'
rm -f hmmexperiments.zip
echo 'zip hmmexperiments.zip expoutput/*'
zip hmmexperiments.zip expoutput/*
