#!/usr/bin/env sh

# hit the reset button.
echo 'rm -rf expoutput3/'
rm -rf expoutput3/
echo 'mkdir -p expoutput3/'
mkdir -p expoutput3/

# for each train txt file, hmm.py will find the corresponding test file.
for datafile in `ls data/basic_features_train.txt | sort`
do
	echo "generating csvs for $datafile ..."
	# test ngrams up to 6.
	# alpha = 1..4, beta = 1..5 ????
	for ng in 4
	do
		for alph in 1
		do
			for bet in 2 2.2 2.5
			do
				echo "generating for n = $ng , alpha = $alph for beta = $bet"
				#echo "hi. $datafile $ng $alph $bet"
				python ./hmm.py $datafile $ng $alph $bet
			done
		done
	done
done

# make a zip
echo 'rm -f hmmexperiments5.zip'
rm -f hmmexperiments5.zip
echo 'zip hmmexperiments5.zip expoutput3/*'
zip hmmexperiments4.zip expoutput3/*
